language: go

go:
  - 1.11.x
  - 1.12.x

script:
  - make
  - make docker-build

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64

after_success:
  - bash <(curl -s https://codecov.io/bash)