apiVersion: v1
kind: Namespace
metadata:
  name: finder
---
apiVersion: v1
kind: Service
metadata:
  name: finder2d
  namespace: finder
spec:
  clusterIP: 10.104.126.254
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: finder2d
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: finder2d
  name: finder2d
  namespace: finder
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: finder2d
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: finder2d
    spec:
      containers:
      - env:
        # - name: FINDER2D_SOURCE
        #   value: "/data/source.txt"
        image: johandry/finder2d
        imagePullPolicy: Always
        name: finder2d
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
