// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatrixName int32

const (
	MatrixName_SOURCE MatrixName = 0
	MatrixName_TARGET MatrixName = 1
)

var MatrixName_name = map[int32]string{
	0: "SOURCE",
	1: "TARGET",
}

var MatrixName_value = map[string]int32{
	"SOURCE": 0,
	"TARGET": 1,
}

func (x MatrixName) String() string {
	return proto.EnumName(MatrixName_name, int32(x))
}

func (MatrixName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Matrix struct {
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Matrix) Reset()         { *m = Matrix{} }
func (m *Matrix) String() string { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()    {}
func (*Matrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Matrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matrix.Unmarshal(m, b)
}
func (m *Matrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matrix.Marshal(b, m, deterministic)
}
func (m *Matrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matrix.Merge(m, src)
}
func (m *Matrix) XXX_Size() int {
	return xxx_messageInfo_Matrix.Size(m)
}
func (m *Matrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Matrix.DiscardUnknown(m)
}

var xxx_messageInfo_Matrix proto.InternalMessageInfo

func (m *Matrix) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Matrix) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Matrix) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Match struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Percentage           float32  `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Match) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Match) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

type GetMatrixRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 MatrixName `protobuf:"varint,2,opt,name=name,proto3,enum=finder2d.v1.MatrixName" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMatrixRequest) Reset()         { *m = GetMatrixRequest{} }
func (m *GetMatrixRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatrixRequest) ProtoMessage()    {}
func (*GetMatrixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetMatrixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatrixRequest.Unmarshal(m, b)
}
func (m *GetMatrixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatrixRequest.Marshal(b, m, deterministic)
}
func (m *GetMatrixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatrixRequest.Merge(m, src)
}
func (m *GetMatrixRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatrixRequest.Size(m)
}
func (m *GetMatrixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatrixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatrixRequest proto.InternalMessageInfo

func (m *GetMatrixRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatrixRequest) GetName() MatrixName {
	if m != nil {
		return m.Name
	}
	return MatrixName_SOURCE
}

type GetMatrixResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 MatrixName `protobuf:"varint,2,opt,name=name,proto3,enum=finder2d.v1.MatrixName" json:"name,omitempty"`
	Matrix               *Matrix    `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMatrixResponse) Reset()         { *m = GetMatrixResponse{} }
func (m *GetMatrixResponse) String() string { return proto.CompactTextString(m) }
func (*GetMatrixResponse) ProtoMessage()    {}
func (*GetMatrixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetMatrixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatrixResponse.Unmarshal(m, b)
}
func (m *GetMatrixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatrixResponse.Marshal(b, m, deterministic)
}
func (m *GetMatrixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatrixResponse.Merge(m, src)
}
func (m *GetMatrixResponse) XXX_Size() int {
	return xxx_messageInfo_GetMatrixResponse.Size(m)
}
func (m *GetMatrixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatrixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatrixResponse proto.InternalMessageInfo

func (m *GetMatrixResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatrixResponse) GetName() MatrixName {
	if m != nil {
		return m.Name
	}
	return MatrixName_SOURCE
}

func (m *GetMatrixResponse) GetMatrix() *Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type LoadMatrixRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 MatrixName `protobuf:"varint,2,opt,name=name,proto3,enum=finder2d.v1.MatrixName" json:"name,omitempty"`
	Matrix               *Matrix    `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoadMatrixRequest) Reset()         { *m = LoadMatrixRequest{} }
func (m *LoadMatrixRequest) String() string { return proto.CompactTextString(m) }
func (*LoadMatrixRequest) ProtoMessage()    {}
func (*LoadMatrixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *LoadMatrixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMatrixRequest.Unmarshal(m, b)
}
func (m *LoadMatrixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMatrixRequest.Marshal(b, m, deterministic)
}
func (m *LoadMatrixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMatrixRequest.Merge(m, src)
}
func (m *LoadMatrixRequest) XXX_Size() int {
	return xxx_messageInfo_LoadMatrixRequest.Size(m)
}
func (m *LoadMatrixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMatrixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMatrixRequest proto.InternalMessageInfo

func (m *LoadMatrixRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoadMatrixRequest) GetName() MatrixName {
	if m != nil {
		return m.Name
	}
	return MatrixName_SOURCE
}

func (m *LoadMatrixRequest) GetMatrix() *Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type LoadMatrixResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadMatrixResponse) Reset()         { *m = LoadMatrixResponse{} }
func (m *LoadMatrixResponse) String() string { return proto.CompactTextString(m) }
func (*LoadMatrixResponse) ProtoMessage()    {}
func (*LoadMatrixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *LoadMatrixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMatrixResponse.Unmarshal(m, b)
}
func (m *LoadMatrixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMatrixResponse.Marshal(b, m, deterministic)
}
func (m *LoadMatrixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMatrixResponse.Merge(m, src)
}
func (m *LoadMatrixResponse) XXX_Size() int {
	return xxx_messageInfo_LoadMatrixResponse.Size(m)
}
func (m *LoadMatrixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMatrixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMatrixResponse proto.InternalMessageInfo

func (m *LoadMatrixResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type SearchRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Percentage           float32  `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Delta                int32    `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SearchRequest) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *SearchRequest) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type SearchResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	TotalMatches         int32    `protobuf:"varint,2,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SearchResponse) GetTotalMatches() int32 {
	if m != nil {
		return m.TotalMatches
	}
	return 0
}

type GetMatchesRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesRequest) Reset()         { *m = GetMatchesRequest{} }
func (m *GetMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchesRequest) ProtoMessage()    {}
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *GetMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesRequest.Unmarshal(m, b)
}
func (m *GetMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesRequest.Merge(m, src)
}
func (m *GetMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchesRequest.Size(m)
}
func (m *GetMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesRequest proto.InternalMessageInfo

func (m *GetMatchesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetMatchesResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Matches              []*Match `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesResponse) Reset()         { *m = GetMatchesResponse{} }
func (m *GetMatchesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMatchesResponse) ProtoMessage()    {}
func (*GetMatchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *GetMatchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesResponse.Unmarshal(m, b)
}
func (m *GetMatchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesResponse.Marshal(b, m, deterministic)
}
func (m *GetMatchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesResponse.Merge(m, src)
}
func (m *GetMatchesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMatchesResponse.Size(m)
}
func (m *GetMatchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesResponse proto.InternalMessageInfo

func (m *GetMatchesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatchesResponse) GetMatches() []*Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

type GetMatchRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchRequest) Reset()         { *m = GetMatchRequest{} }
func (m *GetMatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchRequest) ProtoMessage()    {}
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *GetMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchRequest.Unmarshal(m, b)
}
func (m *GetMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchRequest.Merge(m, src)
}
func (m *GetMatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchRequest.Size(m)
}
func (m *GetMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchRequest proto.InternalMessageInfo

func (m *GetMatchRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatchRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMatchResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Match                *Match   `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Matrix               *Matrix  `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchResponse) Reset()         { *m = GetMatchResponse{} }
func (m *GetMatchResponse) String() string { return proto.CompactTextString(m) }
func (*GetMatchResponse) ProtoMessage()    {}
func (*GetMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *GetMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchResponse.Unmarshal(m, b)
}
func (m *GetMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchResponse.Marshal(b, m, deterministic)
}
func (m *GetMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchResponse.Merge(m, src)
}
func (m *GetMatchResponse) XXX_Size() int {
	return xxx_messageInfo_GetMatchResponse.Size(m)
}
func (m *GetMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchResponse proto.InternalMessageInfo

func (m *GetMatchResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatchResponse) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *GetMatchResponse) GetMatrix() *Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

func init() {
	proto.RegisterEnum("finder2d.v1.MatrixName", MatrixName_name, MatrixName_value)
	proto.RegisterType((*Matrix)(nil), "finder2d.v1.Matrix")
	proto.RegisterType((*Match)(nil), "finder2d.v1.Match")
	proto.RegisterType((*GetMatrixRequest)(nil), "finder2d.v1.GetMatrixRequest")
	proto.RegisterType((*GetMatrixResponse)(nil), "finder2d.v1.GetMatrixResponse")
	proto.RegisterType((*LoadMatrixRequest)(nil), "finder2d.v1.LoadMatrixRequest")
	proto.RegisterType((*LoadMatrixResponse)(nil), "finder2d.v1.LoadMatrixResponse")
	proto.RegisterType((*SearchRequest)(nil), "finder2d.v1.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "finder2d.v1.SearchResponse")
	proto.RegisterType((*GetMatchesRequest)(nil), "finder2d.v1.GetMatchesRequest")
	proto.RegisterType((*GetMatchesResponse)(nil), "finder2d.v1.GetMatchesResponse")
	proto.RegisterType((*GetMatchRequest)(nil), "finder2d.v1.GetMatchRequest")
	proto.RegisterType((*GetMatchResponse)(nil), "finder2d.v1.GetMatchResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xc6, 0xde, 0xec, 0xa6, 0x39, 0x69, 0xd2, 0xed, 0xb4, 0x4a, 0xb6, 0x4b, 0xda, 0x5a, 0x43,
	0x41, 0x51, 0xda, 0xd8, 0xc9, 0xb6, 0x12, 0x68, 0x2f, 0x10, 0xa1, 0x09, 0xb9, 0x61, 0xf9, 0x71,
	0x16, 0x21, 0x21, 0x10, 0x9a, 0xb5, 0x27, 0xf6, 0x94, 0xf5, 0x8c, 0x3b, 0x33, 0xbb, 0x49, 0x14,
	0x55, 0x48, 0x3c, 0x02, 0x5c, 0x20, 0xf1, 0x5a, 0x3c, 0x00, 0x37, 0x48, 0xbc, 0x06, 0xf2, 0x78,
	0xdd, 0xf5, 0xfe, 0x18, 0x51, 0xc1, 0xd5, 0xee, 0x39, 0xf3, 0x9d, 0xef, 0x3b, 0xe7, 0xcc, 0x67,
	0x1b, 0x36, 0x14, 0x95, 0x63, 0x16, 0x50, 0x37, 0x95, 0x42, 0x0b, 0xb4, 0x7e, 0xce, 0x78, 0x48,
	0x65, 0x27, 0x74, 0xc7, 0x87, 0xed, 0x9d, 0x48, 0x88, 0x68, 0x48, 0x3d, 0x92, 0x32, 0x8f, 0x70,
	0x2e, 0x34, 0xd1, 0x4c, 0x70, 0x95, 0x43, 0xdb, 0x4f, 0xcc, 0x4f, 0xb0, 0x1f, 0x51, 0xbe, 0xaf,
	0x2e, 0x48, 0x14, 0x51, 0xe9, 0x89, 0xd4, 0x20, 0x16, 0xd1, 0xf8, 0x0b, 0x68, 0xf4, 0x88, 0x96,
	0xec, 0x12, 0xdd, 0x85, 0xfa, 0x05, 0x0b, 0x75, 0xdc, 0xaa, 0x39, 0xd6, 0x6e, 0xdd, 0xcf, 0x03,
	0xb4, 0x05, 0x8d, 0x98, 0xb2, 0x28, 0xd6, 0xad, 0x15, 0x93, 0x9e, 0x44, 0xa8, 0x05, 0xab, 0x81,
	0xe0, 0x9a, 0x72, 0xdd, 0xaa, 0x3b, 0xd6, 0xee, 0x9a, 0x5f, 0x84, 0xf8, 0x39, 0xd4, 0x7b, 0x44,
	0x07, 0x31, 0xba, 0x09, 0xd6, 0x65, 0xcb, 0x32, 0x55, 0xd6, 0x65, 0x16, 0x5d, 0xb5, 0xec, 0x3c,
	0xba, 0x42, 0x0f, 0x00, 0x52, 0x2a, 0x03, 0xca, 0x35, 0x89, 0xa8, 0x51, 0xb4, 0xfd, 0x52, 0x06,
	0x7f, 0x09, 0xcd, 0x53, 0xaa, 0xf3, 0xce, 0x7c, 0xfa, 0x72, 0x44, 0x95, 0x46, 0x4d, 0xa8, 0x91,
	0x94, 0x19, 0xc6, 0x35, 0x3f, 0xfb, 0x8b, 0x1e, 0xc3, 0x0a, 0x27, 0x09, 0x35, 0xb4, 0x9b, 0x9d,
	0x6d, 0xb7, 0xb4, 0x24, 0x37, 0xaf, 0xfd, 0x8c, 0x24, 0xd4, 0x37, 0x20, 0xfc, 0x23, 0xdc, 0x2e,
	0x51, 0xaa, 0x54, 0x70, 0x45, 0xff, 0x23, 0x27, 0x7a, 0x0c, 0x8d, 0xc4, 0xe4, 0xcc, 0x08, 0xeb,
	0x9d, 0x3b, 0x4b, 0xe0, 0xfe, 0x04, 0x92, 0x35, 0xf0, 0xa9, 0x20, 0xe1, 0xff, 0x39, 0xd4, 0x9b,
	0x35, 0xf0, 0x1e, 0xa0, 0x72, 0x03, 0x55, 0x2b, 0xc0, 0x5f, 0xc3, 0xc6, 0x19, 0x25, 0x32, 0x88,
	0xab, 0x9b, 0x9c, 0xbd, 0x3f, 0x7b, 0xfe, 0xfe, 0x32, 0x33, 0x85, 0x74, 0xa8, 0x49, 0x61, 0x26,
	0x13, 0xe0, 0x53, 0xd8, 0x2c, 0x88, 0x2b, 0xf7, 0xff, 0x0e, 0x6c, 0x68, 0xa1, 0xc9, 0xf0, 0xfb,
	0x24, 0x33, 0x11, 0x55, 0x13, 0xcf, 0xdc, 0x34, 0xc9, 0x5e, 0x9e, 0xc3, 0xef, 0x16, 0x77, 0x99,
	0x45, 0x95, 0x5d, 0xe2, 0x3e, 0xa0, 0x32, 0xac, 0x52, 0xf3, 0x09, 0xac, 0x4e, 0xd5, 0x6a, 0xbb,
	0xeb, 0x1d, 0x34, 0xbf, 0xc6, 0x20, 0xf6, 0x0b, 0x08, 0x7e, 0x0a, 0xb7, 0x0a, 0xd6, 0xea, 0x05,
	0x6d, 0x82, 0xcd, 0xc2, 0x49, 0xef, 0x36, 0x0b, 0xf1, 0x75, 0x61, 0xe8, 0x7f, 0x1c, 0x7e, 0x17,
	0xea, 0x46, 0xc5, 0x14, 0x2e, 0x6f, 0x23, 0x07, 0xbc, 0xd1, 0xc5, 0xef, 0x3d, 0x02, 0x98, 0x3a,
	0x07, 0x01, 0x34, 0xce, 0x3e, 0xff, 0xca, 0x7f, 0x7e, 0xd2, 0x7c, 0x2b, 0xfb, 0xdf, 0x3f, 0xf2,
	0x4f, 0x4f, 0xfa, 0x4d, 0xab, 0xf3, 0xeb, 0x0a, 0xdc, 0xf8, 0x24, 0x27, 0x39, 0x46, 0x3f, 0xc0,
	0xda, 0xeb, 0xa7, 0x05, 0xdd, 0x9f, 0x21, 0x9f, 0x7f, 0x30, 0xdb, 0x0f, 0xaa, 0x8e, 0xf3, 0x39,
	0xf1, 0xc3, 0x9f, 0x7e, 0xff, 0xf3, 0x17, 0xfb, 0x1e, 0xda, 0x36, 0x6f, 0xac, 0xf1, 0xa1, 0x97,
	0xb7, 0x45, 0x95, 0x77, 0x9d, 0x99, 0xf8, 0x15, 0x7a, 0x09, 0x30, 0x35, 0x26, 0x9a, 0xa5, 0x5b,
	0x78, 0x64, 0xda, 0x0f, 0x2b, 0xcf, 0x27, 0x7a, 0xd8, 0xe8, 0xed, 0xe0, 0x2a, 0xbd, 0xae, 0xb5,
	0x87, 0xbe, 0x85, 0x46, 0x6e, 0x45, 0xd4, 0x9e, 0xa1, 0x9b, 0x31, 0x7e, 0xfb, 0xed, 0xa5, 0x67,
	0x13, 0x99, 0x7b, 0x46, 0xe6, 0x0e, 0xde, 0x2c, 0x64, 0x94, 0x39, 0xcf, 0xd8, 0xcf, 0x01, 0xa6,
	0xc6, 0x43, 0xcb, 0xf6, 0x53, 0x32, 0xee, 0xdc, 0x40, 0x8b, 0x8e, 0xc5, 0xdb, 0x46, 0xe9, 0x36,
	0xba, 0x55, 0x1a, 0xc8, 0x30, 0x53, 0xb8, 0x51, 0xc0, 0xd1, 0xce, 0x52, 0x96, 0x42, 0xe3, 0x7e,
	0xc5, 0xe9, 0x44, 0x61, 0xc7, 0x28, 0x6c, 0xa1, 0xbb, 0x73, 0x0a, 0xde, 0x35, 0x0b, 0x5f, 0x7d,
	0xfc, 0x97, 0xfd, 0xf3, 0xd1, 0x1f, 0x36, 0xfa, 0x0e, 0x9a, 0x85, 0x3f, 0x9c, 0xb3, 0xfc, 0xf3,
	0x84, 0x8f, 0x4b, 0x9e, 0x79, 0x14, 0x6b, 0x9d, 0xaa, 0xae, 0xe7, 0x45, 0x4c, 0xc7, 0xa3, 0x81,
	0x1b, 0x88, 0xc4, 0x7b, 0x21, 0x62, 0xc2, 0x43, 0x79, 0xe5, 0x15, 0xf2, 0x6d, 0x54, 0xa4, 0x3e,
	0x8a, 0x12, 0xc2, 0x86, 0x19, 0xaa, 0x53, 0x3b, 0x74, 0x0f, 0xf6, 0x2c, 0xab, 0xd3, 0x24, 0x69,
	0x3a, 0x64, 0x81, 0xf9, 0x42, 0x79, 0x2f, 0x94, 0xe0, 0xdd, 0x85, 0x8c, 0xff, 0x21, 0xd4, 0x9e,
	0x1d, 0x3c, 0x43, 0xef, 0xc3, 0xbe, 0x4f, 0xf5, 0x48, 0x72, 0x1a, 0x3a, 0x17, 0x31, 0xe5, 0x8e,
	0x8e, 0xa9, 0xa3, 0x89, 0x8c, 0xa8, 0x76, 0xf2, 0xfb, 0x76, 0x98, 0x72, 0xb8, 0xd0, 0xce, 0xb9,
	0x18, 0xf1, 0xd0, 0x45, 0x0d, 0x58, 0xf9, 0xcd, 0xb6, 0x56, 0xfd, 0xa3, 0xac, 0xfe, 0x00, 0x75,
	0xe1, 0x83, 0xd9, 0x7a, 0xe2, 0xc8, 0x7c, 0x57, 0x59, 0x1d, 0xe3, 0x63, 0x32, 0x64, 0xa1, 0x23,
	0xa4, 0x93, 0x30, 0xa5, 0x18, 0x8f, 0x9c, 0x94, 0x48, 0x92, 0x50, 0x4d, 0xa5, 0x92, 0x7d, 0xd8,
	0x7a, 0xbd, 0x88, 0x63, 0x11, 0x8c, 0x92, 0xec, 0xad, 0x97, 0x75, 0x88, 0xba, 0xff, 0x66, 0x05,
	0xde, 0x60, 0x28, 0x06, 0x5e, 0x42, 0x94, 0xa6, 0xd2, 0xf3, 0x4f, 0x8e, 0x8e, 0x7b, 0x27, 0x6e,
	0x12, 0x7e, 0x63, 0x8f, 0x0f, 0x07, 0x0d, 0xf3, 0x55, 0x7e, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6b, 0x0a, 0x40, 0xda, 0xff, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Finder2DClient is the client API for Finder2D service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Finder2DClient interface {
	GetMatrix(ctx context.Context, in *GetMatrixRequest, opts ...grpc.CallOption) (*GetMatrixResponse, error)
	LoadMatrix(ctx context.Context, in *LoadMatrixRequest, opts ...grpc.CallOption) (*LoadMatrixResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error)
	GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchResponse, error)
}

type finder2DClient struct {
	cc *grpc.ClientConn
}

func NewFinder2DClient(cc *grpc.ClientConn) Finder2DClient {
	return &finder2DClient{cc}
}

func (c *finder2DClient) GetMatrix(ctx context.Context, in *GetMatrixRequest, opts ...grpc.CallOption) (*GetMatrixResponse, error) {
	out := new(GetMatrixResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/GetMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finder2DClient) LoadMatrix(ctx context.Context, in *LoadMatrixRequest, opts ...grpc.CallOption) (*LoadMatrixResponse, error) {
	out := new(LoadMatrixResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/LoadMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finder2DClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finder2DClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error) {
	out := new(GetMatchesResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/GetMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finder2DClient) GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchResponse, error) {
	out := new(GetMatchResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/GetMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Finder2DServer is the server API for Finder2D service.
type Finder2DServer interface {
	GetMatrix(context.Context, *GetMatrixRequest) (*GetMatrixResponse, error)
	LoadMatrix(context.Context, *LoadMatrixRequest) (*LoadMatrixResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error)
	GetMatch(context.Context, *GetMatchRequest) (*GetMatchResponse, error)
}

// UnimplementedFinder2DServer can be embedded to have forward compatible implementations.
type UnimplementedFinder2DServer struct {
}

func (*UnimplementedFinder2DServer) GetMatrix(ctx context.Context, req *GetMatrixRequest) (*GetMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatrix not implemented")
}
func (*UnimplementedFinder2DServer) LoadMatrix(ctx context.Context, req *LoadMatrixRequest) (*LoadMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMatrix not implemented")
}
func (*UnimplementedFinder2DServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedFinder2DServer) GetMatches(ctx context.Context, req *GetMatchesRequest) (*GetMatchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (*UnimplementedFinder2DServer) GetMatch(ctx context.Context, req *GetMatchRequest) (*GetMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatch not implemented")
}

func RegisterFinder2DServer(s *grpc.Server, srv Finder2DServer) {
	s.RegisterService(&_Finder2D_serviceDesc, srv)
}

func _Finder2D_GetMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).GetMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/GetMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).GetMatrix(ctx, req.(*GetMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder2D_LoadMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).LoadMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/LoadMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).LoadMatrix(ctx, req.(*LoadMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder2D_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder2D_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/GetMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder2D_GetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).GetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/GetMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).GetMatch(ctx, req.(*GetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Finder2D_serviceDesc = grpc.ServiceDesc{
	ServiceName: "finder2d.v1.Finder2D",
	HandlerType: (*Finder2DServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatrix",
			Handler:    _Finder2D_GetMatrix_Handler,
		},
		{
			MethodName: "LoadMatrix",
			Handler:    _Finder2D_LoadMatrix_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Finder2D_Search_Handler,
		},
		{
			MethodName: "GetMatches",
			Handler:    _Finder2D_GetMatches_Handler,
		},
		{
			MethodName: "GetMatch",
			Handler:    _Finder2D_GetMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
