// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatrixName int32

const (
	MatrixName_SOURCE MatrixName = 0
	MatrixName_TARGET MatrixName = 1
)

var MatrixName_name = map[int32]string{
	0: "SOURCE",
	1: "TARGET",
}

var MatrixName_value = map[string]int32{
	"SOURCE": 0,
	"TARGET": 1,
}

func (x MatrixName) String() string {
	return proto.EnumName(MatrixName_name, int32(x))
}

func (MatrixName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Matrix struct {
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Matrix) Reset()         { *m = Matrix{} }
func (m *Matrix) String() string { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()    {}
func (*Matrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Matrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matrix.Unmarshal(m, b)
}
func (m *Matrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matrix.Marshal(b, m, deterministic)
}
func (m *Matrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matrix.Merge(m, src)
}
func (m *Matrix) XXX_Size() int {
	return xxx_messageInfo_Matrix.Size(m)
}
func (m *Matrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Matrix.DiscardUnknown(m)
}

var xxx_messageInfo_Matrix proto.InternalMessageInfo

func (m *Matrix) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Matrix) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Matrix) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetMatrixRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 MatrixName `protobuf:"varint,2,opt,name=name,proto3,enum=finder2d.v1.MatrixName" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMatrixRequest) Reset()         { *m = GetMatrixRequest{} }
func (m *GetMatrixRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatrixRequest) ProtoMessage()    {}
func (*GetMatrixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetMatrixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatrixRequest.Unmarshal(m, b)
}
func (m *GetMatrixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatrixRequest.Marshal(b, m, deterministic)
}
func (m *GetMatrixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatrixRequest.Merge(m, src)
}
func (m *GetMatrixRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatrixRequest.Size(m)
}
func (m *GetMatrixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatrixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatrixRequest proto.InternalMessageInfo

func (m *GetMatrixRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatrixRequest) GetName() MatrixName {
	if m != nil {
		return m.Name
	}
	return MatrixName_SOURCE
}

type GetMatrixResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 MatrixName `protobuf:"varint,2,opt,name=name,proto3,enum=finder2d.v1.MatrixName" json:"name,omitempty"`
	Matrix               *Matrix    `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMatrixResponse) Reset()         { *m = GetMatrixResponse{} }
func (m *GetMatrixResponse) String() string { return proto.CompactTextString(m) }
func (*GetMatrixResponse) ProtoMessage()    {}
func (*GetMatrixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetMatrixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatrixResponse.Unmarshal(m, b)
}
func (m *GetMatrixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatrixResponse.Marshal(b, m, deterministic)
}
func (m *GetMatrixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatrixResponse.Merge(m, src)
}
func (m *GetMatrixResponse) XXX_Size() int {
	return xxx_messageInfo_GetMatrixResponse.Size(m)
}
func (m *GetMatrixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatrixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatrixResponse proto.InternalMessageInfo

func (m *GetMatrixResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetMatrixResponse) GetName() MatrixName {
	if m != nil {
		return m.Name
	}
	return MatrixName_SOURCE
}

func (m *GetMatrixResponse) GetMatrix() *Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type LoadMatrixRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 MatrixName `protobuf:"varint,2,opt,name=name,proto3,enum=finder2d.v1.MatrixName" json:"name,omitempty"`
	Matrix               *Matrix    `protobuf:"bytes,3,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoadMatrixRequest) Reset()         { *m = LoadMatrixRequest{} }
func (m *LoadMatrixRequest) String() string { return proto.CompactTextString(m) }
func (*LoadMatrixRequest) ProtoMessage()    {}
func (*LoadMatrixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *LoadMatrixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMatrixRequest.Unmarshal(m, b)
}
func (m *LoadMatrixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMatrixRequest.Marshal(b, m, deterministic)
}
func (m *LoadMatrixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMatrixRequest.Merge(m, src)
}
func (m *LoadMatrixRequest) XXX_Size() int {
	return xxx_messageInfo_LoadMatrixRequest.Size(m)
}
func (m *LoadMatrixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMatrixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMatrixRequest proto.InternalMessageInfo

func (m *LoadMatrixRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoadMatrixRequest) GetName() MatrixName {
	if m != nil {
		return m.Name
	}
	return MatrixName_SOURCE
}

func (m *LoadMatrixRequest) GetMatrix() *Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type LoadMatrixResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadMatrixResponse) Reset()         { *m = LoadMatrixResponse{} }
func (m *LoadMatrixResponse) String() string { return proto.CompactTextString(m) }
func (*LoadMatrixResponse) ProtoMessage()    {}
func (*LoadMatrixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *LoadMatrixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMatrixResponse.Unmarshal(m, b)
}
func (m *LoadMatrixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMatrixResponse.Marshal(b, m, deterministic)
}
func (m *LoadMatrixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMatrixResponse.Merge(m, src)
}
func (m *LoadMatrixResponse) XXX_Size() int {
	return xxx_messageInfo_LoadMatrixResponse.Size(m)
}
func (m *LoadMatrixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMatrixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMatrixResponse proto.InternalMessageInfo

func (m *LoadMatrixResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterEnum("finder2d.v1.MatrixName", MatrixName_name, MatrixName_value)
	proto.RegisterType((*Matrix)(nil), "finder2d.v1.Matrix")
	proto.RegisterType((*GetMatrixRequest)(nil), "finder2d.v1.GetMatrixRequest")
	proto.RegisterType((*GetMatrixResponse)(nil), "finder2d.v1.GetMatrixResponse")
	proto.RegisterType((*LoadMatrixRequest)(nil), "finder2d.v1.LoadMatrixRequest")
	proto.RegisterType((*LoadMatrixResponse)(nil), "finder2d.v1.LoadMatrixResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0xed, 0xd6, 0xb1, 0x33, 0x81, 0x8a, 0x41, 0x5b, 0xa9, 0x06, 0xb3, 0xa2, 0x09, 0x4d,
	0x1b, 0x8b, 0xd7, 0x32, 0x09, 0xd4, 0x0b, 0x44, 0xa1, 0x65, 0x37, 0x8c, 0x9f, 0x6c, 0xdc, 0x20,
	0x71, 0xe1, 0x26, 0x67, 0x89, 0x47, 0x63, 0x67, 0xb6, 0xdb, 0x81, 0x10, 0x42, 0xe2, 0x11, 0xe0,
	0x8e, 0xd7, 0xe2, 0x01, 0xb8, 0x41, 0x42, 0xe2, 0x29, 0x50, 0x92, 0x75, 0xeb, 0x18, 0x95, 0x40,
	0x70, 0x15, 0x9f, 0xe3, 0xef, 0x9c, 0xf3, 0x7d, 0x5f, 0x6c, 0xc3, 0x05, 0x83, 0x7a, 0x28, 0x02,
	0xf4, 0x52, 0xad, 0xac, 0x22, 0x73, 0x7b, 0x42, 0x86, 0xa8, 0x9b, 0xa1, 0x37, 0x6c, 0xd4, 0x17,
	0x23, 0xa5, 0xa2, 0x3e, 0x32, 0x9e, 0x0a, 0xc6, 0xa5, 0x54, 0x96, 0x5b, 0xa1, 0xa4, 0x29, 0xa0,
	0xf5, 0x9b, 0xf9, 0x27, 0x58, 0x8f, 0x50, 0xae, 0x9b, 0x43, 0x1e, 0x45, 0xa8, 0x99, 0x4a, 0x73,
	0xc4, 0x59, 0xb4, 0xfb, 0x14, 0x2a, 0xdb, 0xdc, 0x6a, 0xf1, 0x9a, 0x5c, 0x81, 0xe9, 0x43, 0x11,
	0xda, 0xb8, 0x56, 0xa6, 0xce, 0xca, 0xb4, 0x5f, 0x04, 0x64, 0x1e, 0x2a, 0x31, 0x8a, 0x28, 0xb6,
	0xb5, 0xa9, 0x3c, 0x7d, 0x14, 0x91, 0x1a, 0xcc, 0x04, 0x4a, 0x5a, 0x94, 0xb6, 0x36, 0x4d, 0x9d,
	0x95, 0x59, 0x7f, 0x14, 0xba, 0xcf, 0xa0, 0xba, 0x85, 0xb6, 0x68, 0xea, 0xe3, 0xc1, 0x00, 0x8d,
	0x25, 0x55, 0x28, 0xf3, 0x54, 0xd4, 0x9c, 0x1c, 0x99, 0x2d, 0xc9, 0x1a, 0x4c, 0x49, 0x9e, 0x60,
	0xad, 0x44, 0x9d, 0x95, 0x8b, 0xcd, 0x05, 0x6f, 0x4c, 0x9f, 0x57, 0xd4, 0x3e, 0xe6, 0x09, 0xfa,
	0x39, 0xc8, 0x7d, 0x0f, 0x97, 0xc6, 0x5a, 0x9a, 0x54, 0x49, 0x83, 0xff, 0xd8, 0x93, 0xac, 0x41,
	0x25, 0xc9, 0x73, 0xb9, 0xde, 0xb9, 0xe6, 0xe5, 0xdf, 0xc0, 0xfd, 0x23, 0x48, 0x46, 0xe0, 0x91,
	0xe2, 0xe1, 0xff, 0x14, 0xf5, 0x77, 0x04, 0x6e, 0x00, 0x19, 0x27, 0x30, 0xc9, 0x82, 0xd5, 0x65,
	0x80, 0x93, 0x41, 0x04, 0xa0, 0xb2, 0xf3, 0xe4, 0xb9, 0xff, 0xa0, 0x5b, 0x3d, 0x97, 0xad, 0x77,
	0xdb, 0xfe, 0x56, 0x77, 0xb7, 0xea, 0x34, 0x7f, 0x38, 0x70, 0xfe, 0x61, 0x31, 0xac, 0x43, 0x5e,
	0xc1, 0xec, 0xb1, 0xb9, 0xe4, 0xda, 0x29, 0x12, 0xbf, 0xfe, 0xc7, 0xfa, 0xf5, 0x49, 0xdb, 0x05,
	0x21, 0x77, 0xe9, 0xc3, 0x97, 0x6f, 0x9f, 0x4a, 0x57, 0xc9, 0x42, 0x7e, 0x36, 0x87, 0x0d, 0x56,
	0xd0, 0x47, 0xc3, 0xde, 0x66, 0x9a, 0xdf, 0x91, 0x03, 0x80, 0x13, 0x1d, 0xe4, 0x74, 0xbb, 0x33,
	0x0e, 0xd7, 0x97, 0x26, 0xee, 0x1f, 0xcd, 0x73, 0xf3, 0x79, 0x8b, 0xee, 0xa4, 0x79, 0x2d, 0x67,
	0xf5, 0xfe, 0xf7, 0xd2, 0xc7, 0xf6, 0xd7, 0x12, 0x79, 0x09, 0xd5, 0x91, 0x64, 0xba, 0x53, 0xdc,
	0x2d, 0xb7, 0x33, 0x66, 0xc3, 0x72, 0x6c, 0x6d, 0x6a, 0x5a, 0x8c, 0x45, 0xc2, 0xc6, 0x83, 0x9e,
	0x17, 0xa8, 0x84, 0xed, 0xab, 0x98, 0xcb, 0x50, 0xbf, 0x61, 0x23, 0x1a, 0x75, 0x32, 0x4a, 0xdd,
	0x8b, 0x12, 0x2e, 0xfa, 0x19, 0xaa, 0x59, 0x6e, 0x78, 0x1b, 0xab, 0x8e, 0xd3, 0xac, 0xf2, 0x34,
	0xed, 0x8b, 0x20, 0xbf, 0x5e, 0x6c, 0xdf, 0x28, 0xd9, 0x3a, 0x93, 0xf1, 0xef, 0x42, 0x79, 0x73,
	0x63, 0x93, 0xdc, 0x86, 0x75, 0x1f, 0xed, 0x40, 0x4b, 0x0c, 0xe9, 0x61, 0x8c, 0x92, 0xda, 0x18,
	0xa9, 0xe5, 0x3a, 0x42, 0x4b, 0x0b, 0x09, 0x54, 0x18, 0x2a, 0x95, 0xa5, 0x7b, 0x6a, 0x20, 0x43,
	0x8f, 0x54, 0x60, 0xea, 0x73, 0xc9, 0x99, 0xf1, 0xdb, 0x59, 0xfd, 0x06, 0x69, 0xc1, 0x9d, 0xd3,
	0xf5, 0x9c, 0xea, 0xc2, 0xb3, 0xac, 0x4e, 0xc8, 0x21, 0xef, 0x8b, 0x90, 0x2a, 0x4d, 0x13, 0x61,
	0x8c, 0x90, 0x11, 0x4d, 0xb9, 0xe6, 0x09, 0x5a, 0xd4, 0x46, 0xef, 0xc2, 0xfc, 0xb1, 0x11, 0x1d,
	0x15, 0x0c, 0x12, 0x94, 0xc5, 0x93, 0x40, 0x5a, 0x7f, 0x62, 0x01, 0xeb, 0xf5, 0x55, 0x8f, 0x25,
	0xdc, 0x58, 0xd4, 0xcc, 0xef, 0xb6, 0x3b, 0xdb, 0x5d, 0x2f, 0x09, 0x5f, 0x94, 0x86, 0x8d, 0x5e,
	0x25, 0x7f, 0x52, 0x6e, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x62, 0x9c, 0x7a, 0xbc, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Finder2DClient is the client API for Finder2D service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Finder2DClient interface {
	GetMatrix(ctx context.Context, in *GetMatrixRequest, opts ...grpc.CallOption) (*GetMatrixResponse, error)
	LoadMatrix(ctx context.Context, in *LoadMatrixRequest, opts ...grpc.CallOption) (*LoadMatrixResponse, error)
}

type finder2DClient struct {
	cc *grpc.ClientConn
}

func NewFinder2DClient(cc *grpc.ClientConn) Finder2DClient {
	return &finder2DClient{cc}
}

func (c *finder2DClient) GetMatrix(ctx context.Context, in *GetMatrixRequest, opts ...grpc.CallOption) (*GetMatrixResponse, error) {
	out := new(GetMatrixResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/GetMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finder2DClient) LoadMatrix(ctx context.Context, in *LoadMatrixRequest, opts ...grpc.CallOption) (*LoadMatrixResponse, error) {
	out := new(LoadMatrixResponse)
	err := c.cc.Invoke(ctx, "/finder2d.v1.Finder2D/LoadMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Finder2DServer is the server API for Finder2D service.
type Finder2DServer interface {
	GetMatrix(context.Context, *GetMatrixRequest) (*GetMatrixResponse, error)
	LoadMatrix(context.Context, *LoadMatrixRequest) (*LoadMatrixResponse, error)
}

// UnimplementedFinder2DServer can be embedded to have forward compatible implementations.
type UnimplementedFinder2DServer struct {
}

func (*UnimplementedFinder2DServer) GetMatrix(ctx context.Context, req *GetMatrixRequest) (*GetMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatrix not implemented")
}
func (*UnimplementedFinder2DServer) LoadMatrix(ctx context.Context, req *LoadMatrixRequest) (*LoadMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMatrix not implemented")
}

func RegisterFinder2DServer(s *grpc.Server, srv Finder2DServer) {
	s.RegisterService(&_Finder2D_serviceDesc, srv)
}

func _Finder2D_GetMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).GetMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/GetMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).GetMatrix(ctx, req.(*GetMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder2D_LoadMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Finder2DServer).LoadMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finder2d.v1.Finder2D/LoadMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Finder2DServer).LoadMatrix(ctx, req.(*LoadMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Finder2D_serviceDesc = grpc.ServiceDesc{
	ServiceName: "finder2d.v1.Finder2D",
	HandlerType: (*Finder2DServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatrix",
			Handler:    _Finder2D_GetMatrix_Handler,
		},
		{
			MethodName: "LoadMatrix",
			Handler:    _Finder2D_LoadMatrix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
